/*
 *
 * Structure constants
 *
 */

export const DEFAULT_ACTION = "app/Structure/DEFAULT_ACTION";

export const ADD_FILE_ACTION = "app/Structure/ADD_FILE_ACTION";

export const UPDATE_FIELD_ACTION = "app/Structure/UPDATE_FIELD_ACTION";

export const SUBMIT_FORM_REQUEST_ACTION =
  "app/Structure/SUBMIT_FORM_REQUEST_ACTION";
export const SUBMIT_FORM_RESPONSE_ACTION =
  "app/Structure/SUBMIT_FORM_RESPONSE_ACTION";

export const GET_TRANSACTIONS_REQUEST_ACTION =
  "app/Structure/GET_TRANSACTIONS_REQUEST_ACTION";
export const GET_TRANSACTIONS_RESPONSE_ACTION =
  "app/Structure/GET_TRANSACTIONS_RESPONSE_ACTION";

export const TOGGLE_MENU_ACTION = "app/Structure/TOGGLE_MENU_ACTION";

export const CHANGE_TAB_ACTION = "app/Structure/CHANGE_TAB_ACTION";

export const GET_FILES_REQUEST_ACTION =
  "app/Structure/GET_FILES_REQUEST_ACTION";
export const GET_FILES_RESPONSE_ACTION =
  "app/Structure/GET_FILES_RESPONSE_ACTION";

export const SUBMIT_DECISION_REQUEST_ACTION =
  "app/Structure/SUBMIT_DECISION_REQUEST_ACTION";
export const SUBMIT_DECISION_RESPONSE_ACTION =
  "app/Structure/SUBMIT_DECISION_RESPONSE_ACTION";
